---
- name: Generate html
  template:
    src: templates/index.html.j2
    dest: "/home/{{ ansible_user }}/webapp/index.html"
- name: "Launching an HTTPD Container"
  docker_container:
#      name: apache-server
    name: nginx-server
    image: nginx
#      image: httpd
    state: started
    ports:
#        - "{{ port }}:80"
      - "8000:80"
    volumes:
       - /home/{{ ansible_user }}/webapp:/usr/share/nginx/html/
#      - /home/{{ ansible_user }}/webapp:/usr/local/apache2/htdocs/
...